from enum import Enum


class ErrorReason(str, Enum):
    INVALID_DATE = "INVALID_DATE"
    DUPLICATE_CATEGORY = "DUPLICATE_CATEGORY"
    DUPLICATE_TOPUP = "DUPLICATE_TOPUP"
    SUBSCRIPTIONS_NOT_FOUND = "SUBSCRIPTIONS_NOT_FOUND"
